WellsFargoSampleSln/WellsFargoSamplePrj/Models/ConsolidatedCountryInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using App.BusinessLayer;

namespace WellsFargoSamplePrj.Models
{
    public class ConsolidatedCountryInfo
    {
        public Country Country { get; set; }
        public string  StateList { get; set; }

    }
}

WellsFargoSampleSln/WellsFargoSamplePrj/Controllers/GeographyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.BusinessLayer;
using WellsFargoSamplePrj.Models;

namespace WellsFargoSamplePrj.Controllers
{
    public class GeographyController : Controller
    {
        // GET: Geography
        public ActionResult StateInfo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StateInfo(string CountryCode)
        {
            ConsolidatedCountryInfo _consolidatedData = new ConsolidatedCountryInfo();
            var countryHandler = new CountryHandler();
            var states = countryHandler.GetStatesListByCountry(CountryCode);
            states = states.Replace("\n", "");           
            Country countryInfo = countryHandler.GetCountryInfo(CountryCode);

            _consolidatedData.Country = countryInfo;
            _consolidatedData.StateList = states;
            return View(_consolidatedData);

           
        }
    }
}

WellsFargoSampleSln/WellsFargoSamplePrj/Views/Geography/StateInfo.cshtml
@model WellsFargoSamplePrj.Models.ConsolidatedCountryInfo
@using App.BusinessLayer;


@{
    ViewBag.Title = "StateInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>State Geographical Information</h2>

@using (Html.BeginForm("StateInfo", "Geography", FormMethod.Post))
{

    <div class="row">
        <form role="form" class="form-inline">
            <div class="form-group">
                <label id="lblCountry" for="" class="control-label inline form-group">Enter Country Code</label>
                <input type="text" class="focused form-control text-uppercase inline" name="CountryCode" id="CountryCode" />
                <button type="submit" id="btnCountrySearch" class="btn btn-primary inline">Submit</button>

            </div>

        </form>

    </div>
    @*<table>

            <tr>
                <td>Enter Country Code: </td>
                <td>@Html.TextBox("CountryCode")</td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" value="Submit"></td>
            </tr>
        </table>*@
}



@if(@Model!=null){

    <div class="form">
        <div class="form-group">
            <div class="row">
                <div class="col=md-6">
                    <label id="lblCountry" class="control-label inline form-group" for="CountryName">
                        Country Name
                    </label>
                </div>
                <div class="col-md-4"><span class="form-control" name="CountryName" />@Model.Country.Name</div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col=md-6">
                    <label id="lblContinent" class="control-label inline form-group" for="Continent">
                        Continent Name
                    </label>
                </div>
                <div class="col-md-4"><span class="form-control" name="Continent" />@Model.Country.Continent</div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col=md-6">
                    <label id="lblPopulation" class="control-label inline form-group" for="PopulationCount">
                        Population
                    </label>
                </div>
                <div class="col-md-4"><span class="form-control" name="PopulationCount" />@Model.Country.population</div>
            </div>
        </div>
            
        </div>
    }


  @if (@Model != null)
  {


        <div class="container" style="padding-top:20px;">
            <div class="row">

                <div>
                    <table id="tblState" class=" table table-striped table-bordered  datatable">
                        <thead></thead>
                        <tbody></tbody>
                        <tfoot></tfoot>
                    </table>
                </div>
            </div>
        </div>
        <script>
        $(document).ready(function () {
            
                var statesResponse = '@Model.StateList';
                var states = JSON.parse(statesResponse.replace(/&quot;/g, '"'));
                console.log(states.RestResponse);
                StateUI.ViewCountryData(states.RestResponse.result);
        });

        </script>

        <script type="text/javascript" src="@Url.Content("/AppJs/StateUI.js")"></script>

}


WellsFargoSampleSln/WellsFargoSamplePrj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @RenderSection("scripts", required: false)

    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    <footer class="navbar-fixed-bottom">
        <p>&copy; @DateTime.Now.Year A Sample MVC Application</p>
    </footer>
</body>
</html>